# Generated by Django 3.2.4 on 2021-06-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hooks', models.IntegerField()),
                ('hooksPerClick', models.IntegerField()),
                ('hooksPerSecond', models.IntegerField()),
                ('replayPrice', models.IntegerField()),
                ('dragonclawHookPrice', models.IntegerField()),
                ('dendiSetPrice', models.IntegerField()),
            ],
        ),
    ]
